name: build_test_deploy

on:
  push:

jobs:
  build-unix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          repository: MiniZinc/libminizinc
      - uses: actions/checkout@v2
        with:
          repository: Gecode/gecode
      - uses: actions/checkout@v2
        with:
          repository: chuffed/chuffed
      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .
