name: build_test_deploy

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, windows-2016, macos-10.15]
    steps:
      - uses: actions/checkout@v2
        with:
          repository: Gecode/gecode
      - name: configure
        run: mkdir build && cd build && cmake ..
      - name: build
        run: |
          cmake --build build
          ls -l build/bin/
          ls -l build/
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: gecode-${{ matrix.os }}
          path: build/bin/**
      - uses: actions/checkout@v2
        with:
          repository: chuffed/chuffed
      - name: configure
        run: mkdir build && cd build && cmake ..
      - name: build
        run: |
          cmake --build build
          ls -l build/*.dir/
          ls -l build/Debug/
          ls -l build/Win32/
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: chuffed-${{ matrix.os }}
          path: build/bin/**/fzn-chuffed
