name: build_test_deploy

on:
  push:

jobs:
  build-unix:
    runs-on: ubuntu-latest
    steps:
      - name: knock knock
        run: |
          ls -lRt
      - uses: actions/checkout@v2
        with:
          repository: MiniZinc/libminizinc
      - name: Compilation libminizinc
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .
      - name: What is there
        run: |
          ls -lRt
      - uses: actions/checkout@v2
        with:
          repository: Gecode/gecode
      - name: Building gecode
        run: |
          configure
          make
      - uses: actions/checkout@v2
        with:
          repository: chuffed/chuffed
      - name: CMake chuffed
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .
