name: build_test_deploy

on:
  push:

jobs:
  build-unix:
    runs-on: ubuntu-latest
    steps:
      - name: knock knock
        run: |
          pwd
          ls -lRt
      - uses: actions/checkout@v2
        with:
          repository: Gecode/gecode
      - name: configure
        run: mkdir build && cd build && cmake ..
      - name: build
        run: |
            cmake --build build
            ldd bin/fzn-gecode
            ls -lrt build/bin/
            ls -lrt build/lib/

  build-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, windows-2016]
    
    steps:
      - uses: actions/checkout@v2
        with:
          repository: Gecode/gecode
      - name: configure
        run: mkdir build && cd build && cmake ..
      - name: build
        run: cmake --build build --config Debug
