name: build_test_deploy

on:
  push:

jobs:
  build-unix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: knock knock
        run: |
          pwd
          ls -lRt
      - uses: actions/checkout@v2
        with:
          repository: Gecode/gecode
      - name: configure
        run: mkdir build && cd build && cmake ..
      - name: build
        run: |
            cmake --build build
            ldd build/bin/fzn-gecode
            ls -lrt build/bin/
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./gecode-linux.tar.gz
          name: build/bin/**

  build-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, windows-2016]
    steps:
      - uses: actions/checkout@v2
        with:
          repository: Gecode/gecode
      - name: configure
        run: mkdir build && cd build && cmake ..
      - name: build
        run: cmake --build build --config Debug
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./gecode-windows.zip
          name: build/bin/**

  build-macosx:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15]
    steps:
      - uses: actions/checkout@v2
        with:
          repository: Gecode/gecode
      - name: configure
        run: mkdir build && cd build && cmake ..
      - name: build
        run: cmake --build build
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./gecode-macosx.tgz
          name: build/bin/**
