name: build_test_deploy

on:
  push:

jobs:
  build-unix:
    runs-on: ubuntu-latest
    steps:
      - name: knock knock
        run: |
          pwd
          ls -lRt
      - uses: actions/checkout@v2
        with:
          repository: Gecode/gecode
      - name: Building gecode
        run: |
          pwd
          mkdir build
          cd build
          cmake ..
          cmake --build .
      - name: winding up
        run: |
          pwd
          ls -l
